EinvoiceIntegration.Sample/Controllers/B2C/B2CInvoiceGetIssueController.cs
using EinvoiceIntegration.Models.B2C;
using EinvoiceIntegration.Services.B2C;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers
{
    public class B2CInvoiceGetIssueController : Controller
    {
        // GET: B2CInvoiceGetIssue
        public ActionResult Index()
        {
            return View(new GetIssueModel() { MerchantID = 2000132 });
        }

        [HttpPost]
        public ActionResult Index(GetIssueModel model)
        {
            var _service = new B2CInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Stage,
                B2CEnum = Enum.B2C.B2CInvoiceMethod.GetIssue,
                HashKey = "ejCk326UnaZWKisg",
                HashIV = "q9jcZX8Ib9LM8wYk"
            };

            ViewBag.Message = _service.PostRtnJson<GetIssueModel, GetIssueResult>(model);
            return View();
        }
    }
}

EinvoiceIntegration.Sample/Views/B2CInvoiceGetIssue/Index.cshtml
@using EinvoiceIntegration.Enum
@model EinvoiceIntegration.Models.B2C.GetIssueModel
@{
    ViewBag.Title = "綠界科技";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {
        $('#reset').click(function () {
            location.href='@Url.Action("Index")';
        });
    });
</script>
@using (Html.BeginForm("Index", "B2CInvoiceGetIssue", FormMethod.Post))
{
    <h2>查詢開立</h2>
    <div class="div1">
        <table class="table">
            <tr>
                <th>
                    廠商編號(必填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.MerchantID)
                </td>
            </tr>
            <tr>
                <th>
                    特店自訂編號(必填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.RelateNumber)
                </td>
            </tr>
            <tr>
                <th>
                    發票開立日期(必填) yyyy-MM-dd：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.InvoiceDate)
                </td>
            </tr>
            <tr>
                <th>
                    發票號碼(必填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.InvoiceNo)
                </td>
            </tr>
        </table>
    </div>

    <div class="buttonPanel">
        <button type="submit">送出</button>
        <button type="button" id="reset">重新填寫</button>
    </div>
    <h2>顯示結果</h2>
    <span id="answer" class="div1" style="word-wrap:break-word;">@ViewBag.message</span>
}