EinvoiceIntegration.Sample/Controllers/B2B/B2BInvoiceAllowanceConfirmController.cs
using EinvoiceIntegration.Models.B2B;
using EinvoiceIntegration.Services.B2B;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers
{
    public class B2BInvoiceAllowanceConfirmController : Controller
    {
        // GET: B2BInvoiceAllowanceConfirm
        public ActionResult Index()
        {
            return View(new AllowanceConfirmModel() { MerchantID = 2000132 });
        }

        [HttpPost]
        public ActionResult Index(AllowanceConfirmModel model)
        {
            var _service = new B2BInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Stage,
                B2BEnum = Enum.B2B.B2BInvoiceMethod.AllowanceConfirm,
                HashKey = "ejCk326UnaZWKisg",
                HashIV = "q9jcZX8Ib9LM8wYk"
            };

            ViewBag.Message = _service.PostRtnJson<AllowanceConfirmModel, AllowanceConfirmResult>(model);
            return View();
        }
    }
}

EinvoiceIntegration.Sample/Views/B2BInvoiceAllowanceConfirm/Index.cshtml
@using EinvoiceIntegration.Enum
@model EinvoiceIntegration.Models.B2B.AllowanceConfirmModel
@{
    ViewBag.Title = "綠界科技";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {
        $('#reset').click(function () {
            location.href='@Url.Action("Index")';
        });
    });
</script>
@using (Html.BeginForm("Index", "B2BInvoiceAllowanceConfirm", FormMethod.Post))
{
    <h2>折讓-接收確認</h2>
    <div class="div1">
        <table class="table">
            <tr>
                <th>
                    廠商編號(必填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.MerchantID)
                </td>
            </tr>
            <tr>
                <th>
                    折讓單號(必填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.AllowanceNo)
                </td>
            </tr>
            <tr>
                <th>
                    備註(選填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.Remark)
                </td>
            </tr>
        </table>
    </div>

    <div class="buttonPanel">
        <button type="submit">送出</button>
        <button type="button" id="reset">重新填寫</button>
    </div>
    <h2>顯示結果</h2>
    <span id="answer" class="div1" style="word-wrap:break-word;">@ViewBag.message</span>
}