EinvoiceIntegration.Sample/Controllers/B2B/B2BInvoiceIssueController.cs
using EinvoiceIntegration.Models.B2B;
using EinvoiceIntegration.Sample.Models.B2B;
using EinvoiceIntegration.Services.B2B;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers
{
    public class B2BInvoiceIssueController : Controller
    {
        // GET: B2BInvoiceIssue
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string InvoiceIssue(InvoiceIssue issue)
        {
            var _service = new B2BInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Stage,
                B2BEnum = Enum.B2B.B2BInvoiceMethod.Issue,
                HashKey = "ejCk326UnaZWKisg",
                HashIV = "q9jcZX8Ib9LM8wYk"
            };

            int seqNumber = 0;
            var items = new List<InvoiceIssueModel.Item>();
            issue.Items.ForEach(t => items.Add(new InvoiceIssueModel.Item
            {
                ItemSeq = seqNumber + 1,
                ItemName = t.ItemName,
                ItemCount = t.ItemCount,
                ItemTax = t.ItemTax,
                ItemWord = t.ItemWord,
                ItemPrice = t.ItemPrice,
                ItemAmount = t.ItemAmount,
                ItemRemark = t.ItemRemark
            }));

            var model = new InvoiceIssueModel
            {
                MerchantID = issue.MerchantID,
                RelateNumber = issue.RelateNumber,
                ClearanceMarkEnum = issue.ClearanceMark,
                CustomerIdentifier = issue.CustomerIdentifier,
                CustomerAddress = issue.CustomerAddress,
                CustomerTel = issue.CustomerTel,
                CustomerEmail = issue.CustomerEmail,
                SalesAmount = issue.SalesAmount,
                TaxAmount = issue.TaxAmount,
                TotalAmount = issue.TotalAmount,
                TaxTypeEnum = issue.TaxType,
                TrackTypeEnum = issue.InvType,
                Items = items,
                SpecialTaxTypeEnum = issue.TaxType == Enum.TaxTypeEnum.SpecTax && issue.InvType == Enum.TrackTypeEnum.Special ? issue.SpecialTaxType : Enum.SpecialTaxTypeEnum.None,
                ZeroTaxRateReasonEnum = issue.ZeroTaxRateReason
            };

            return _service.PostRtnJson<InvoiceIssueModel, InvoiceIssueResult>(model);
        }
    }
}

EinvoiceIntegration.Sample/Controllers/B2B/B2BInvoicePrintController.cs
using EinvoiceIntegration.Models.B2B;
using EinvoiceIntegration.Services.B2B;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers.B2B
{
    public class B2BInvoicePrintController : Controller
    {
        // GET: B2BInvoicePrintController
        public ActionResult Index()
        {
            return View(new InvoicePrintModel() { MerchantID = 3089976 });
        }

        [HttpPost]
        public ActionResult Index(InvoicePrintModel model)
        {
            var _service = new B2BInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Dev,
                B2BEnum = Enum.B2B.B2BInvoiceMethod.InvoicePrint,
                HashKey = "K8dZeuJUp3Qt67Bc",
                HashIV = "j83wrQWXC4c3mdPc"
            };

            ViewBag.Message = _service.Post<InvoicePrintModel>(model);

            return View();
        }
    }
}

EinvoiceIntegration.Sample/Controllers/B2C/B2CInvoiceIssueController.cs
using EinvoiceIntegration.Models.B2C;
using EinvoiceIntegration.Sample.Models.B2C;
using EinvoiceIntegration.Services.B2C;
using EinvoiceIntegration.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers
{
    public class B2CInvoiceIssueController : Controller
    {
        // GET: B2CInvoice
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string InvoiceIssue(InvoiceIssue issue)
        {
            var _service = new B2CInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Stage,
                B2CEnum = Enum.B2C.B2CInvoiceMethod.Issue,
                HashKey = "ejCk326UnaZWKisg",
                HashIV = "q9jcZX8Ib9LM8wYk"
            };

            var items = new List<InvoiceIssueModel.Item>();
            issue.Items.ForEach(t => items.Add(new InvoiceIssueModel.Item
            {
                ItemName = t.ItemName,
                ItemCount = t.ItemCount,
                ItemWord = t.ItemWord,
                ItemPrice = t.ItemPrice,
                ItemTaxType = t.ItemTaxType.ToString(),
                ItemAmount = t.ItemAmount,
                ItemRemark = t.ItemRemark
            }));

            var model = new InvoiceIssueModel
            {
                MerchantID = issue.MerchantID,
                RelateNumber = issue.RelateNumber,
                ClearanceMarkEnum = issue.ClearanceMark,
                CarrierTypeEnum = issue.CarrierType,
                CarrierNum = issue.CarrierNum,
                PrintEnum = issue.Print,
                DonationEnum = issue.Donation,
                CustomerID = issue.CustomerID,
                CustomerIdentifier = issue.CustomerIdentifier,
                CustomerAddr = issue.CustomerAddr,
                CustomerName = issue.CustomerName,
                CustomerPhone = issue.CustomerPhone,
                CustomerEmail = issue.CustomerEmail,
                SalesAmount = issue.SalesAmount,
                SpecialTaxTypeEnum = issue.TaxType == Enum.TaxTypeEnum.SpecTax && issue.InvType == Enum.TrackTypeEnum.Special ? issue.SpecialTaxType : Enum.SpecialTaxTypeEnum.None,
                ChannelPartnerEnum = issue.ChannelPartner,
                LoveCode = issue.LoveCode,
                VatEnum = issue.Vat,
                TaxTypeEnum = issue.TaxType,
                TrackTypeEnum = issue.InvType,
                Items = items,
                ProductServiceID = issue.ProductServiceID,
                ZeroTaxRateReasonEnum = issue.ZeroTaxRateReason
            };

            return _service.PostRtnJson<InvoiceIssueModel, InvoiceIssueResult>(model);
        }
    }
}

EinvoiceIntegration.Sample/Controllers/B2C/B2CInvoicePrintController.cs
using EinvoiceIntegration.Models.B2C;
using EinvoiceIntegration.Services.B2C;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers.B2C
{
    public class B2CInvoicePrintController : Controller
    {
        // GET: B2CInvoicePrint
        public ActionResult Index()
        {
            return View(new InvoicePrintModel() { MerchantID = 2000132 });
        }

        [HttpPost]
        public ActionResult Index(InvoicePrintModel model)
        {
            var _service = new B2CInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Stage,
                B2CEnum = Enum.B2C.B2CInvoiceMethod.InvoicePrint,
                HashKey = "ejCk326UnaZWKisg",
                HashIV = "q9jcZX8Ib9LM8wYk"
            };

            ViewBag.Message = _service.PostRtnJson<InvoicePrintModel, InvoicePrintResult>(model);

            return View();
        }
    }
}

EinvoiceIntegration.Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>

</head>

<body>
    <div class="page">

        <div id="header">

            <div id="menucontainer">
                <h2>B2C</h2>
                <ul id="menu">
                    <li>@Html.ActionLink("一般開立", "Index", "B2CInvoiceIssue")</li>
                    <li>@Html.ActionLink("延遲或觸發開立發票", "Index", "B2CInvoiceDelayIssue")</li>
                    <li>@Html.ActionLink("編輯延遲開立發票", "Index", "B2CInvoiceEditDelayIssue")</li>
                    <li>@Html.ActionLink("開立折讓(紙本)", "Index", "B2CInvoiceAllowance")</li>
                    <li>@Html.ActionLink("開立折讓(線上)", "Index", "B2CInvoiceAllowanceByCollegiate")</li>
                    <li>@Html.ActionLink("發票作廢", "Index", "B2CInvoiceInvalid")</li>
                    <li>@Html.ActionLink("折讓作廢", "Index", "B2CInvoiceAllowanceInvalid")</li>
                    <li>@Html.ActionLink("查詢發票", "Index", "B2CInvoiceGetIssue")</li>
                    <li>@Html.ActionLink("查詢作廢", "Index", "B2CInvoiceGetInvalid")</li>
                    <li>@Html.ActionLink("查詢折讓明細(紙本)", "Index", "B2CInvoiceGetAllowance")</li>
                    <li>@Html.ActionLink("查詢折讓明細(紙本多筆)", "Index", "B2CInvoiceGetAllowanceList")</li>
                    <li>@Html.ActionLink("查詢折讓明細(線上)", "Index", "B2CInvoiceGetAllowanceByCollegiate")</li>
                    <li>@Html.ActionLink("查詢折讓作廢明細", "Index", "B2CInvoiceGetAllowanceInvalid")</li>
                </ul>
                <ul id="menu">
                    <li>@Html.ActionLink("發送通知", "Index", "B2CInvoiceNotify")</li>
                    <li>@Html.ActionLink("Trigger觸發或延遲開立發票", "Index", "B2CInvoiceTriggerIssue")</li>
                    <li>@Html.ActionLink("檢查手機條碼", "Index", "B2CInvoiceCheckBarcode")</li>
                    <li>@Html.ActionLink("檢查愛心碼", "Index", "B2CInvoiceCheckLoveCode")</li>
                    <li>@Html.ActionLink("查詢字軌", "Index", "B2CInvoiceGetInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("查詢財政部配號結果", "Index", "B2CInvoiceGetGovInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("新增字軌號碼", "Index", "B2CInvoiceAddInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("設定字軌號碼狀態", "Index", "B2CInvoiceUpdateInvoiceWordStatus")</li>
                    <li>@Html.ActionLink("取得發票字軌號碼(離線)", "Index", "B2CInvoiceGetOfflineInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("上傳開立發票(離線)", "Index", "B2CInvoiceOfflineIssue")</li>
                    <li>@Html.ActionLink("上傳作廢發票(離線)", "Index", "B2CInvoiceOfflineInvalid")</li>
                    <li>@Html.ActionLink("發票列印", "Index", "B2CInvoicePrint")</li>
                    <li>@Html.ActionLink("管理離線機台(離線)", "Index", "B2CInvoiceOfflineMerchantPosSetting")</li>
                </ul>
                <ul id="menu">
                    <li>@Html.ActionLink("查詢離線機台(離線)", "Index", "B2CInvoiceQueryOfflineMerchantPosSetting")</li>
                    <li>@Html.ActionLink("取得發票配號(離線)", "Index", "B2CInvoiceGetOfflineInvoiceWordSettingNumber")</li>
                    <li>@Html.ActionLink("取得廠商資訊(離線)", "Index", "B2CInvoiceGetOfflineMerchantInfo")</li>
                    <li>@Html.ActionLink("查詢特定多筆發票", "Index", "B2CInvoiceGetIssueList")</li>
                    <li>@Html.ActionLink("統一編號驗證", "Index", "B2CInvoiceGetCompanyNameByTaxID")</li>
                </ul>
            </div>

            <div id="menucontainer">
                <h2>B2B</h2>
                <ul id="menu">
                    <li>@Html.ActionLink("一般開立", "Index", "B2BInvoiceIssue")</li>
                    <li>@Html.ActionLink("開立折讓", "Index", "B2BInvoiceAllowance")</li>
                    <li>@Html.ActionLink("發票作廢", "Index", "B2BInvoiceInvalid")</li>
                    <li>@Html.ActionLink("折讓作廢", "Index", "B2BInvoiceCancelAllowance")</li>
                    <li>@Html.ActionLink("退回", "Index", "B2BInvoiceReject")</li>
                    <li>@Html.ActionLink("查詢發票", "Index", "B2BInvoiceGetIssue")</li>
                    <li>@Html.ActionLink("查詢作廢", "Index", "B2BInvoiceGetInvalid")</li>
                    <li>@Html.ActionLink("查詢折讓明細", "Index", "B2BInvoiceGetAllowance")</li>
                    <li>@Html.ActionLink("查詢折讓作廢明細", "Index", "B2BInvoiceGetAllowanceInvalid")</li>
                    <li>@Html.ActionLink("查詢退回", "Index", "B2BInvoiceGetReject")</li>
                    <li>@Html.ActionLink("發送通知", "Index", "B2BInvoiceNotify")</li>
                    <li>@Html.ActionLink("折讓-接收確認", "Index", "B2BInvoiceAllowanceConfirm")</li>
                    <li>@Html.ActionLink("折讓作廢-接收確認", "Index", "B2BInvoiceCancelAllowanceConfirm")</li>
                    <li>@Html.ActionLink("退回-接收確認", "Index", "B2BInvoiceRejectConfirm")</li>
                    <li>@Html.ActionLink("查詢折讓確認", "Index", "B2BInvoiceGetAllowanceConfirm")</li>
                </ul>
                <ul id="menu">
                    <li>@Html.ActionLink("查詢折讓作廢確認", "Index", "B2BInvoiceGetAllowanceInvalidConfirm")</li>
                    <li>@Html.ActionLink("查詢作廢確認", "Index", "B2BInvoiceGetInvalidConfirm")</li>
                    <li>@Html.ActionLink("查詢開立確認", "Index", "B2BInvoiceGetIssueConfirm")</li>
                    <li>@Html.ActionLink("查詢退回確認", "Index", "B2BInvoiceGetRejectConfirm")</li>
                    <li>@Html.ActionLink("查詢字軌", "Index", "B2BInvoiceGetInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("查詢財政部配號結果", "Index", "B2BInvoiceGetGovInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("新增字軌號碼", "Index", "B2BInvoiceAddInvoiceWordSetting")</li>
                    <li>@Html.ActionLink("設定字軌號碼狀態", "Index", "B2BInvoiceUpdateInvoiceWordStatus")</li>
                    <li>@Html.ActionLink("發票列印", "Index", "B2BInvoicePrint")</li>
                    <li>@Html.ActionLink("發票下載PDF檔", "Index", "B2BInvoiceDownloadB2BPdf")</li>
                    <li>@Html.ActionLink("統一編號驗證", "Index", "B2BInvoiceGetCompanyNameByTaxID")</li>
                </ul>
            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>