EinvoiceIntegration.Sample/Controllers/B2C/B2CInvoiceGetGovInvoiceWordSettingController.cs
using EinvoiceIntegration.Models.B2C;
using EinvoiceIntegration.Services.B2C;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EinvoiceIntegration.Sample.Controllers.B2C
{
    public class B2CInvoiceGetGovInvoiceWordSettingController : Controller
    {
        // GET: B2CInvoiceGetGovInvoiceWordSetting
        public ActionResult Index()
        {
            return View(new GetGovInvoiceWordSettingModel() { MerchantID = 2000132 });
        }

        [HttpPost]
        public ActionResult Index(GetGovInvoiceWordSettingModel model)
        {
            var _service = new B2CInvoiceService
            {
                EnvEnum = Enum.EnvironmentEnum.Stage,
                B2CEnum = Enum.B2C.B2CInvoiceMethod.GetGovInvoiceWordSetting,
                HashKey = "ejCk326UnaZWKisg",
                HashIV = "q9jcZX8Ib9LM8wYk"
            };

            ViewBag.Message = _service.PostRtnJson<GetGovInvoiceWordSettingModel, GetGovInvoiceWordSettingResult>(model);

            return View();
        }
    }
}

EinvoiceIntegration.Sample/Views/B2CInvoiceGetGovInvoiceWordSetting/Index.cshtml
@using EinvoiceIntegration.Enum
@model EinvoiceIntegration.Models.B2C.GetGovInvoiceWordSettingModel
@{
    ViewBag.Title = "綠界科技";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {
        $('#reset').click(function () {
            location.href='@Url.Action("Index")';
        });
    });
</script>
@using (Html.BeginForm("Index", "B2CInvoiceGetGovInvoiceWordSetting", FormMethod.Post))
{
    <h2>查詢財政部配號結果</h2>
    <div class="div1">
        <table class="table" style="word-wrap:break-word;">
            <tr>
                <th>
                    廠商編號(必填)：
                </th>
                <td>
                    @Html.TextBoxFor(m => m.MerchantID)
                </td>
            </tr>
            <tr>
                <th>
                    發票年度(必填)：<br />
                    僅可查詢去年、當年與明年的發票年度(格式為民國年 ex:110)
                </th>
                <td>
                    @Html.TextBoxFor(m => m.InvoiceYear)
                </td>
            </tr>
        </table>
    </div>

    <div class="buttonPanel">
        <button type="submit">送出</button>
        <button type="button" id="reset">重新填寫</button>
    </div>
    <h2>顯示結果</h2>
    <span id="answer" class="div1" style="word-wrap:break-word;">@ViewBag.message</span>
}